<li class="designer_list">
                   <div class="list_head">
                        <div class="phonto_border"><img src="images/designer/wusong_400x250.jpg" alt="吴松" class="phonto"></div>
                        <div class="philosophy">
                            <h1 class="title">设计理念</h1>
                            <div class="txt">[field:concept/]</div>
                        </div>
                   </div>
                   <div class="info">
                       <h1 class="title">
                           <span class="bg_l"></span>
                           <span class="bg_r"></span>
                       </h1>
                       <dl>
                           <dd>
                               <span class="sub_title">设计师：</span>
                               <p class="txt">吴松</p>
                           </dd>
                           <dd>
                               <span class="sub_title">出生年月：</span>
                               <p class="txt">1986年12月8日</p>
                           </dd>
                           <dd>
                               <span class="sub_title">毕业院校：</span>
                               <p class="txt">2006毕业于江西庐山西海（国际）<br>艺术学院（原丰良国际艺术学院）</p>
                           </dd>
                           <dd>
                               <span class="sub_title">专业：</span>
                               <p class="txt">环境艺术室内设计</p>
                           </dd>
                           
                       </dl>
                   </div>
               </li>