<li class="designer_list">
                   <div class="list_head">
                        <div class="phonto_border"><img src="[field:img/]" alt="长葛格林娜" class="phonto"></div>
                        <div class="philosophy">
                            <h1 class="title">设计理念</h1>
                            <div class="txt">[field:concept/]</div>
                        </div>
                   </div>
                   <div class="info">
                       <h1 class="title">
                           <span class="bg_l"></span>
                           <span class="bg_r"></span>
                       </h1>
                       <dl>
                           <dd>
                               <span class="sub_title">设计师：</span>
                               <p class="txt">[field:name/]</p>
                           </dd>
                           <dd>
                               <span class="sub_title">出生年月：</span>
                               <p class="txt">[field:datebirth/]</p>
                           </dd>
                           <dd>
                               <span class="sub_title">毕业院校：</span>
                               <p class="txt">[field:school/]</p>
                           </dd>
                           <dd>
                               <span class="sub_title">专业：</span>
                               <p class="txt">[field:professional/]</p>
                           </dd>
                           
                       </dl>
                   </div>
               </li>