<h1 class="title">[field:typename/]</h1>
                            <p class="info visible_desktop">
                            在使用独一无二的先装修后付款的模式下，为了让客户能够满意付款，吴松装饰形成了创新型的监理系统。

<!-- {dede:sql sql="select * From zx_archives limit 10"}
·[field:title/]

{/dede:sql} -->
{dede:sql sql='Select content from zx_arctype where id=4'}
    [field:content /]
{/dede:sql}
                            </p>
                            
                            <a href="[field:typeurl/]" class="mod_btn more" target="_blink">
                                <span class="icon_plus "></span>
                                <span class="txt">查看更多</span>
                            </a>