<h1 class="title">[field:typename/]</h1>
                            <p class="info visible_desktop">
                            我们公司贯彻先装修再付款的理念，让客户觉得满意了再付款。
<!-- 　　{dede:channel typeid='3' type='son'}
　[field:description/]
　　{/dede:channel} -->

                            </p>
                            
                            <a href="[field:typeurl/]" class="mod_btn more" target="_blink">
                                <span class="icon_plus "></span>
                                <span class="txt">查看更多</span>
                            </a>