
    <m:item name='普通文章' ischannel='1' link='content_list.php?channelid=1' linkadd='article_add.php?channelid=1' channelid='1' rank='' target='main' />
  <m:item name='公司简介' ischannel='1' link='content_list.php?channelid=17' linkadd='archives_add.php?channelid=17' channelid='17' rank='' target='main' />
  <m:item name='优势' ischannel='1' link='content_list.php?channelid=18' linkadd='archives_add.php?channelid=18' channelid='18' rank='' target='main' />
  <m:item name='设计师' ischannel='1' link='content_list.php?channelid=19' linkadd='archives_add.php?channelid=19' channelid='19' rank='' target='main' />
  <m:item name='装修案例' ischannel='1' link='content_list.php?channelid=20' linkadd='archives_add.php?channelid=20' channelid='20' rank='' target='main' />
  <m:item name='先装修后付款' ischannel='1' link='content_list.php?channelid=21' linkadd='archives_add.php?channelid=21' channelid='21' rank='' target='main' />
  <m:item name='全员监控' ischannel='1' link='content_list.php?channelid=22' linkadd='archives_add.php?channelid=22' channelid='22' rank='' target='main' />

  <m:item name='专题管理' ischannel='1' link='content_s_list.php' linkadd='spec_add.php' channelid='-1' rank='spec_New' target='main' />
