<h1 class="title">[field:typename /]</h1>
                            <p class="info visible_desktop">
                            [field:description /][field:info /][field:description function="cn_substr(@me,60)"/]</p>
                            <a href="[field:typelink /]" class="mod_btn more">
                                <span class="icon_plus"></span>
                                <span class="txt">查看更多</span>
                            </a>