<h1 class="title">[field:typename/]</h1>
                            <p class="info visible_desktop">
                            设计源于生活，<br>
                            生活赋予设计。</p>
                            <a href="[field:typeurl/]" class="mod_btn more" target="_blink">
                                <span class="icon_plus "></span>
                                <span class="txt">查看更多</span>
                            </a>