<?php
$z[0]=Array("global","",470,502);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",581,613);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",659,691);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",739,771);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",817,849);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",895,927);
$z[5][4]['name']="cfg_templets_skin";

?>