<field:concept itemname="设计理念" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="" page="">
</field:concept>
<field:name itemname="设计师名字" autofield="1" notsend="0" type="textchar" isnull="true" islist="0" default=""  maxlength="" page="">
</field:name>
<field:datebirth itemname="出生日期（比如：1990年11月3日）" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="" page="">
</field:datebirth>
<field:school itemname="毕业学院" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="" page="">
</field:school>
<field:professional itemname="专业" autofield="1" notsend="0" type="textchar" isnull="true" islist="0" default=""  maxlength="" page="">
</field:professional>
