<?php
$z[0]=Array("global","",289,321);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",398,430);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",491,523);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",560,592);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",631,663);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",904,936);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",1254,1286);
$z[6][4]['name']="cfg_templets_skin";

?>