<?php
$z[0]=Array("global","",513,545);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",624,656);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",702,734);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",782,814);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",860,892);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",938,970);
$z[5][4]['name']="cfg_templets_skin";

?>