<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,17,1,'5YWs5Y+45LuL57uN');
$cfg_Cs[2]=array(0,18,1,'5LyY5Yq/');
$cfg_Cs[3]=array(2,21,1,'5YWI6KOF5L+u5ZCO5LuY5qy+');
$cfg_Cs[4]=array(2,22,1,'5YWo5ZGY55uR5o6n');
$cfg_Cs[5]=array(2,19,1,'6K6+6K6h5biI');
$cfg_Cs[6]=array(2,20,1,'6KOF5L+u5qGI5L6L');
$cfg_Cs[7]=array(6,20,1,'5a625bGF5bqX6ZO6');
$cfg_Cs[8]=array(6,20,1,'5Yqe5YWs5bqX6ZO6');
$cfg_Cs[9]=array(6,20,1,'6YWS5bqX5Lya5omA');
$cfg_Cs[10]=array(0,1,1,'6IGU57O75oiR5Lus');
?>